'use strict';
console.log("hoge");
phina.globalize();

const GAME_SCREEN_WIDTH = 1280;
const GAME_SCREEN_HEIGHT = 768;
const GAME_SCREEN_WIDTH_HALF = GAME_SCREEN_WIDTH / 2;
const GAME_SCREEN_HEIGHT_HALF = GAME_SCREEN_HEIGHT / 2;
const GAME_SCREEN_TOP = 0;
const GAME_SCREEN_BOTTOM = GAME_SCREEN_HEIGHT;
const GAME_SCREEN_LEFT = 0;
const GAME_SCREEN_RIGHT = GAME_SCREEN_WIDTH;

const BASE_GRID = 64;
const BASE_GRID_HALF = BASE_GRID/ 2;
const BASE_GRID_QUARTER = BASE_GRID_HALF/ 2;
const CHARACTER_GRID = 64;
const MIN_TILES = 32;

const PLAYER_SPEED = 5;